apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ${NAME}
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationNonProduction
  replicas: 2
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: L-KSBM-C37J2R
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: ${IMAGE}
        imagePullPolicy: Always
