apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ${NAME}
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KSBM-C87FU2
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.2.0-r2
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: ${IMAGE}
        imagePullPolicy: Always
